POST http://124.222.229.234:2929/login HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"3333"
}
###
GET http://127.0.0.1:9001/user/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VyIjoie1wiaWRcIjpudWxsLFwidXNlcm5hbWVcIjpcImFkbWluXCIsXCJwYXNzd29yZFwiOm51bGwsXCJzdGF0dXNcIjpudWxsLFwicm9sZXNcIjpbe1wiaWRcIjo2LFwicm9sZU5hbWVcIjpcIlJPTEVfQURNSU5cIixcInJvbGVEZXNjXCI6XCLnrqHnkIblkZhcIn0se1wiaWRcIjo5LFwicm9sZU5hbWVcIjpcIlJPTEVfVVNFUlwiLFwicm9sZURlc2NcIjpcIuaZrumAmueUqOaIt1wifV19IiwianRpIjoiTkdZeVpUQmlZV1V0TURneE55MDBNRE5oTFdJMk1UUXROVFpsWm1ZeE5tWTFORGMxIiwiZXhwIjoxNjUzMTAyMjgwfQ.lckgMqQ4AxQ2JabsKYK6J5M3qHghWbuw7tFkTi-faqqqlBrvdAa2m5EQ9b0CfRrhr6iTb5OgXHBULq42wYDQbpS-l6kt406wpLW5ZtoPWPKoemyg6CRjc2XD4zFYA6eGhpBnZ418RbrY0y_RsIiTqBzOTXHjs4-NKal8V6qiqkXb4M8AzdO19JVbueBY4OFGLTLqypxqbhRTR3OiYdFPW2RPGUgZK7JpJGz1cfa3M2dZ-q4eFXQlbtu4zek1CrARcgZb88Oja-7F1cPWpTjEDRHnsG--cjjEW2665Emdl8ePuxVY-aFI4kBcSip-GocYVk7Un-k64a-Jzl7tj_kaNw

###
GET http://127.0.0.1:9002/web/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VyIjoie1wiaWRcIjpudWxsLFwidXNlcm5hbWVcIjpcImFkbWluXCIsXCJwYXNzd29yZFwiOm51bGwsXCJzdGF0dXNcIjpudWxsLFwicm9sZXNcIjpbe1wiaWRcIjo2LFwicm9sZU5hbWVcIjpcIlJPTEVfQURNSU5cIixcInJvbGVEZXNjXCI6XCLnrqHnkIblkZhcIn0se1wiaWRcIjo5LFwicm9sZU5hbWVcIjpcIlJPTEVfVVNFUlwiLFwicm9sZURlc2NcIjpcIuaZrumAmueUqOaIt1wifV19IiwianRpIjoiTkdZeVpUQmlZV1V0TURneE55MDBNRE5oTFdJMk1UUXROVFpsWm1ZeE5tWTFORGMxIiwiZXhwIjoxNjUzMTAyMjgwfQ.lckgMqQ4AxQ2JabsKYK6J5M3qHghWbuw7tFkTi-faqqqlBrvdAa2m5EQ9b0CfRrhr6iTb5OgXHBULq42wYDQbpS-l6kt406wpLW5ZtoPWPKoemyg6CRjc2XD4zFYA6eGhpBnZ418RbrY0y_RsIiTqBzOTXHjs4-NKal8V6qiqkXb4M8AzdO19JVbueBY4OFGLTLqypxqbhRTR3OiYdFPW2RPGUgZK7JpJGz1cfa3M2dZ-q4eFXQlbtu4zek1CrARcgZb88Oja-7F1cPWpTjEDRHnsG--cjjEW2665Emdl8ePuxVY-aFI4kBcSip-GocYVk7Un-k64a-Jzl7tj_kaNw
